name: Run domeggook script every 6 hours

on:
  schedule:
    - cron: '0 */6 * * *'  # 매일 6시간마다 실행 (UTC 기준)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install bcrypt pybase64 requests Pillow

      - name: Run script
        run: |
          python domeggook_to_smartsstore.py

      - name: Upload output files
        uses: actions/upload-artifact@v4
        with:
          name: product-files
          path: |
            product.txt
            product_result.txt
